# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20151214_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='end_date',
            field=models.DateTimeField(verbose_name=b'end date'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
