# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170509_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artwork',
            new_name='Product',
        ),
    ]
