# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20170509_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='teacher',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auction',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
