# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-09 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20170509_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='background_color',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
