# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 19:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auction_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='end_date',
        ),
        migrations.AddField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='end date(UTC)'),
        ),
    ]
